### ISSUE TITLE
Double `Unmeasurable` prefix in components of mixture sub-graphs

### ISSUE THREAD

**Issue by larryshamalama** [aesara-devs/aeppl#157]
Mixture sub-graphs are identified by [mixture_replace](https://github.com/aesara-devs/aeppl/blob/main/aeppl/mixture.py#L241-L242) and each component is assigned to be unmeasurable [as per here](https://github.com/aesara-devs/aeppl/blob/main/aeppl/mixture.py#L274). However, in defining the stack, tensors which are combined go through a similar procedure [here](https://github.com/aesara-devs/aeppl/blob/main/aeppl/tensor.py#L175), hence why the type `UnmeasurableUnmeasurableNormalRV` occurs. This becomes an issue when trying to use functions such as [`aesara.graph.basic.equal_computations`](https://github.com/aesara-devs/aesara/blob/main/aesara/graph/basic.py#L1634) to check if Op types are identical.

Below is an example of this error:

```python
import aesara.tensor as at
from aeppl.opt import construct_ir_fgraph

srng = at.random.RandomStream(seed=2320)

I_rv = srng.bernoulli(0.5, name="I")
X_rv = srng.normal(-10., 0.1, name="X")
Y_rv = srng.normal(10., 0.1, name="Y")

# mixture from stack
Z_rv = at.stack([X_rv, Y_rv])[I_rv]
Z_rv.name = "Z"
z_vv = Z_rv.clone()

i_vv = I_rv.clone()

fgraph, _, _ = construct_ir_fgraph({Z_rv: z_vv, I_rv: i_vv})

fgraph.outputs[0] # Z-mixture
fgraph.outputs[0].owner.inputs # [NoneConst, ScalarFromTensor.0, X, Y]
type(fgraph.outputs[0].owner.inputs[2].owner.op) # aesara.tensor.random.basic.UnmeasurableUnmeasurableNormalRV
```

**Comment by larryshamalama** [comment]
I'm not sure what is the preferred approach to address this. Is the problem outlined above inherent to the assignment of nodes to be `Unmeasurable` or general to the `assign_custom_measurable_outputs` function? In other words, below are some ideas:

- Check in [`mixture_replace`](https://github.com/aesara-devs/aeppl/blob/main/aeppl/mixture.py#L274) if components are already deemed `Unmeasurable`;
- Check if `op_type.__name__.startswith(type_prefix)` and return the original `node` (or even `new_node` but without the prefix inserted?).

**Comment by brandonwillard** [comment]
It might also be possible to return the original node in the call to `assign_custom_measurable_outputs` when the `Op` is already assigned the given `measurable_outputs_fn` in the `_get_measurable_outputs` dispatch.
