### ISSUE TITLE
We should probably not sum `joint_logprob` by default

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aeppl#162]
Currently, `joint_logprob` returns a scalar whatever the number of dimensions of the observation variable by default:

```python
from aeppl import joint_logprob
import aesara.tensor as at
import numpy as np

srng = at.random.RandomStream(0)
a_rv = srng.normal(0, 1, size=10)

a_vv = a_rv.clone()
logprob = joint_logprob({a_rv: a_vv})

print(logprob.eval({a_vv: np.ones(10)}))
# -14.189385332046724
```

I think that this behavior is confusing. To understand why, consider two cases in which we&rsquo;d want the observation variable above to be a vector:

1.  If we have multiple (10) observations and would like to compute the joint probability of these observations as a function of the parameters, e.g. the likelihood.
2.  We want to sample from the posterior distribution with 10 chains.

In the first case, summation by default will work. In the second it will fail, and one will have to do instead:

```python
logprob = joint_logprob({a_rv: a_vv}, sum=False)
print(logprob.eval({a_vv: np.ones(10)}))
# [-1.41893853 -1.41893853 -1.41893853 -1.41893853 -1.41893853 -1.41893853  -1.41893853 -1.41893853 -1.41893853 -1.41893853]
```

I would rather have `joint_logprob` return a vector in this case and require the user to explicitly sum the result when computing the log-likelihood. This make *intent* more explicit in the code, and avoids the use of a keyword argument.

As an aside, I wouldn't have so much of a problem with the summation by default if we had a canonical way to handle multiple chains e.g. with something like `logprobs = elemwise(logprob)(np.ones(10))` (pseudo code). Maybe this exists and I am not aware of it?

**Comment by ricardoV94** [comment]
The reason we sum by default is that `sum=False` is doing something "unsafe" at the moment with multiple variables. It is calling elemwise add across the multiple independent logp terms, which may have different shapes or be otherwise unrelated dimension-wise.

**Comment by ricardoV94** [comment]
Any interest in changing the default to `sum=False` and returning the tuple of logprobs when multiple variables are requested?

**Comment by brandonwillard** [comment]
> Any interest in changing the default to `sum=False` and returning the tuple of logprobs when multiple variables are requested?

Don't see why not.
