### ISSUE TITLE
Add affine transform support to `total_logprob`

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aeppl#18]
With a new `local_optimizer` addition to `RVSinker`, we could add support for affine/linear transforms of `RandomVariables`.

In other words, the following could be made to work:
```python
import aesara.tensor as at

from aeppl import joint_logprob


a, b = at.scalars("ab")
Y_rv = a * at.random.normal(0, 1, name="Y") + b

y_val = Y_rv.type()
logp = joint_logprob(Y_rv, {Y_rv: y_val})
```

**Comment by ricardoV94** [comment]
I have been playing with this one already. Let me see if I can push something in the next couple of days.

**Comment by brandonwillard** [comment]
Since this functionality overlaps directly with the existing transforms, we should implement it in that framework&mdash;updating it if need be, of course.

For a very general framework, we could finally introduce [`kanren`](https://github.com/pythological/kanren) as a means of determining the underlying transform function and its inverse (for a subset of known functions).  This would provide us with the `RVTransform.forward` and `RVTransform.backward` implementations automatically, and the log Jacobian determinant is already covered by existing Aesara `Op`s.
