### ISSUE TITLE
Implement log-probability for `StudentTRV`

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aeppl#185]
Once https://github.com/aesara-devs/aesara/pull/1211 is merged.

**Comment by brandonwillard** [comment]
Is this about implement another `StudentTRV` in AePPL?

**Comment by rlouf** [comment]
> Is this about implement another `StudentTRV` in AePPL?

Another?

**Comment by brandonwillard** [comment]
A `StudentTRV` is being added to Aesara in https://github.com/aesara-devs/aesara/pull/1211, so I'm wondering if/why we have an issue here for it.

**Comment by brandonwillard** [comment]
OK, I'm assuming this is in regard to a `logprob`, now that I've noticed the labels.
