### ISSUE TITLE
Replace remaining docstring instances of `factorized_joint_logprob`

### ISSUE THREAD

**Issue by larryshamalama** [aesara-devs/aeppl#228]
In #196, `factorized_joint_logprob` has been renamed to `conditional_logprob`. However, there are still some occurrences in docstrings where `factorized_joint_logprob` shows up:

https://github.com/aesara-devs/aeppl/blob/fb6ffc51a282d21d134d691400d477366a3d14cc/aeppl/abstract.py#L80-L82

https://github.com/aesara-devs/aeppl/blob/7890228715320c2d1ff6989ff522829b5d6411ba/aeppl/mixture.py#L273-L275

https://github.com/aesara-devs/aeppl/blob/696effab5df9df3be45c1f7395a54ce35fa1d197/tests/test_dist.py#L412-L413

**Comment by brandonwillard** [comment]
Thanks for pointing that out!

**Comment by Kd-Here** [comment]
Can I help in that @brandonwillard 
Just give little detail of that. It will my first contro to open project

**Comment by rlouf** [comment]
Of course, you'll just have to replace the occurrences of `factorized_joint_logprob` with `conditional_logrob`. Open a PR and we can help you there if you need to.

**Comment by rlouf** [comment]
Closed by #228
