### ISSUE TITLE
Make transforms more flexible

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aeppl#32]
The current transforms rewrite looks for all RVs that have a standard TransformedRV and automatically converts those (and the respective value variables). To plugin `aeppl` into PyMC3 in the future, we probably need something more flexible where we specify **what** transforms we want to apply to **which** value variables.

This should also allow us to apply transforms to value variables that are associated with dynamically derived RVs.

For example:
```python
import aesara.tensor as at
from aeppl import joint_logprob

shift_rv = at.random.normal(0, 1)
y_rv = at.random.exponential(1) + shift

shift = shift_rv.clone()
y = y_rv.clone()

logp = joint_logprob(y_rv, {y_rv: y, shift_rv: shift}, transfoms={y: Interval(shift_rv, None)})
```
I think the logic could still be implemented as a custom "rewrite", I just used a new keyword to simplify the example.

**Comment by brandonwillard** [comment]
> To plugin `aeppl` into PyMC3 in the future, we probably need something more flexible where we specify **what** transforms we want to apply to **which** value variables.

How is this feature required in order to support PyMC3?  Currently, PyMC3 automatically applies these same transforms and does not have the flexibility you describe.

**Comment by ricardoV94** [comment]
> unless you're only talking about the `transform` keyword.  

That's exactly what I was talking about

> Better yet, since the transforms are currently applied by an independent rewrite/optimizer object, we should probably add those custom transform specifications to the rewriter/optimizer object itself.

I was thinking the same, notice I wrote that in my original comment. The extra keyword was just to make the example more succinct.

I think we are on the same page here
