### ISSUE TITLE
Docstrings tracking issue

### ISSUE THREAD

**Issue by ericmjl** [aesara-devs/aeppl#4]
I'm happy to work on docstrings if you find this task to be tedium. :smile:

Let me know, @brandonwillard!

**Comment by brandonwillard** [comment]
Of course we're open to docstrings; that would be much appreciated!

**Comment by brandonwillard** [comment]
Yes, that sounds great; however, I don't know the extent to which we can detail all of the intent and architecture, since&mdash;for at least the latter&mdash;that's still being worked-out.

**Comment by ericmjl** [comment]
Got it. What is your take on docstrings for the log prob functions, @brandonwillard? Necessary or unnecessary?

**Comment by ericmjl** [comment]
Thanks @brandonwillard. Let me comb through the log-prob implementations to see if there's anything noteworthy there. I'll start off with that.
