### ISSUE TITLE
Allow joint_logprob to receive a list of variables

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aeppl#40]
It seems natural that we could compute the logprob graph for several independent variables (e.g, if we have more than one likelihood term, or disconnected "potential" terms). 

```python
x_rv = at.random.uniform(0, 1, name="x")
y_rv = at.random.uniform(0, 5, name="y")
z_rv = at.random.uniform(0, 10, name="z")

x = x_rv.clone()
y = y_rv.clone()
z = z_rv.clone()

joint_logprob(
    [x_rv, y_rv, z_rv],
    {x_rv: x, y_rv: y, z_rv: z},
)
```
However, I am afraid this could lead to double counting issues...

Also, right now we can stack RVs, but I guess this is limited by the shapes of the RVs

```python
joint_logprob(
    at.stack([x_rv, y_rv, z_rv]),
    {x_rv: x, y_rv: y, z_rv: z},
)
```

**Comment by brandonwillard** [comment]
We could definitely do this without much trouble.  It eas actually how I originally planned to implement `joint_logprob`.

**Comment by ricardoV94** [comment]
Also of we have a hierarchical graph it would ideally work the same even if we pass all the RVs as input

```python
x_rv = at.random.uniform(0, 1, name="x")
y_rv = at.random.uniform(0, 5, name="y")
z_rv = at.random.uniform(x_rv, y_rv, name="z")

x = x_rv.clone()
y = y_rv.clone()
z = z_rv.clone()

# The following should be equivalent 
joint_logprob(
    [x_rv, y_rv, z_rv],
    {x_rv: x, y_rv: y, z_rv: z},
)

joint_logprob(
    [z_rv],
    {x_rv: x, y_rv: y, z_rv: z},
)
```

**Comment by brandonwillard** [comment]
> That would make it much more straightforward to integrate with PyMC3
> 
> Hopefully it's just a question of changing the expected input and adding one or two tests.

Yeah, that's basically it.
