### ISSUE TITLE
Allow for `Potential` terms in `joint_logprob`

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aeppl#48]
Potential terms are arbitrary terms that are added to the logprob graph without "values".
Would something like this make sense?

```python
x_rv = at.random.normal()
potential = at.switch(x_rv < 0, -np.inf, 0)

x = x_rv.clone()

joint_logprob([x_rv, potential], {x_rv: x, potential: None})
```

**Comment by brandonwillard** [comment]
What's required beyond the use of Aesara's existing addition `Op` on the output of `joint_logprob`?

**Comment by ricardoV94** [comment]
RV -> value replacement

**Comment by brandonwillard** [comment]
> RV -> value replacement, otherwise there is no reason why it would require joint_logprob

We have a function that does that part alone, no?

**Comment by ricardoV94** [comment]
Sure we do, it's the `rv_to_values`

**Comment by ricardoV94** [comment]
Reopening, another reason to parse Potentials in `joint_logprob` would be when dealing with transforms

**Comment by brandonwillard** [comment]
Don't forget that transforms are independent of `joint_logprob`.

**Comment by rlouf** [comment]
What does the model in the first message represents mathematically speaking?

**Comment by ricardoV94** [comment]
> What does the model in the first message represents mathematically speaking?

An unnormalized halfnormal

**Comment by rlouf** [comment]
> An unnormalized halfnormal

Sorry for the second stupid question, but what would the logprob of that graph look like in your mind?

**Comment by ricardoV94** [comment]
The same as

```python
x = at.random.normal("x")
x_vv = at.scalar("x_vv")

logp = joint_logprob({x: x_vv}) + at.switch(x_vv < 0, -np.inf, 0)
```

The point being that the potentials are first defined in terms of RVs, and then get replaced by the respective value (or potentially transformed) variables.

**Comment by ricardoV94** [comment]
By the way I am not very married to this idea. The concern is just to help users bridge the RV-Value duality more easily. Perhaps improving `rvs_to_values` to accommodate value transforms would be a better approach.

**Comment by rlouf** [comment]
> Perhaps improving `rvs_to_values` to accommodate value transforms would be a better approach.

I think that makes more sense
