### ISSUE TITLE
Update `joint_logprob` docstring

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aeppl#59]
Since `joint_logprob` will be a likely point-of-entry for most people, we should make its signature more explicit and find a way to reuse parts of the docstring from `factorized_joint_logprob`.

**Comment by sudarsan2k5** [comment]
@brandonwillard I'd like to work on this; could you please assign it to me?

**Comment by rlouf** [comment]
This is being resolved in #213 unfortunately
