### ISSUE TITLE
Implement HMC-related `RandomVariable` transforms

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aeppl#7]
We now have a good framework for easily implementing the HMC-related `RandomVariable` transforms (or, as the ML people have (re)labeled them, "normalizing flows").  

We can start by creating a single Aesara rewrite (e.g. using `aesara.graph.opt.local_optimizer`) that replaces transformed `RandomVariable`s with an intermediate form in the "sample-space" graph (i.e. the first input to `joint_logprob`).  That intermediate form could be a new `RandomVariable` type (e.g. `TransformedRV`) with a `_logprob` dispatch that implements the change-of-variables formula (including the Jacobian).  This new `RandomVariable` type would essentially be a wrapper around the original `RandomVariable` that only serves to provide a distinct `_logprob` dispatch.

**Comment by ricardoV94** [comment]
@brandonwillard are you already working on this wrapper `TransformedRV`, or have a rough idea of how it should be implemented? 

I think that after this is inplace I could start experimenting with some of the basic `logp` derivations that I started on the PyMC3 repo. I just don't have a very precise idea of how the skeleton of the `TransformedRV` (and/or others alike) should look like.

**Comment by brandonwillard** [comment]
> @brandonwillard are you already working on this kind of `TransformedRV` wrapper, or have a rough idea of how it should be implemented?

I'll set something up in the next couple days.
