### ISSUE TITLE
Support mixtures defined with `switch`

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aeppl#77]
We need to add support for mixtures defined using the `Elemwise` +  `Switch` `Op`.

The following is a simple example that isn't supported:
```python
import aesara.tensor as at

from aeppl.joint_logprob import factorized_joint_logprob


srng = at.random.RandomStream(seed=2320)

I_rv = srng.bernoulli(0.5, size=10, name="I")
X_rv = srng.normal(0, 1, name="X")
Y_rv = srng.gamma(0.5, 0.5, size=10, name="Y")

Z_rv = at.switch(I_rv, X_rv, Y_rv)
Z_rv.name = "Z"

z_vv = Z_rv.clone()
i_vv = I_rv.clone()
logp_parts = factorized_joint_logprob({Z_rv: z_vv, I_rv: i_vv})
```

**Comment by ricardoV94** [comment]
> > Should we just canonicalize these to a `at.stack([X_rv, Y_rv])[I_rv]`?
> 
> Good question.  My first thought is that we would also need a "specialization" (or something similar) that undoes that canonicalization when/if `np.switch` is more efficient to compute than the stacking and indexing.

You mean when the switch is not actually associated with a value variable? Or do you mean the logprob expression should be defined with a switch because that could be more efficient?

**Comment by brandonwillard** [comment]
> You mean when the switch is not actually associated with a value variable? Or do you mean the logprob expression should be defined with a switch because that could be more efficient?

The latter.
