### ISSUE TITLE
Revert #82

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aeppl#83]
See https://github.com/aesara-devs/aeppl/issues/82#issuecomment-954978400.

**Comment by ricardoV94** [comment]
https://github.com/aesara-devs/aeppl/pull/82#issuecomment-955031299

**Comment by brandonwillard** [comment]
Following up from https://github.com/aesara-devs/aeppl/pull/82#issuecomment-955059640, what's the case for extending `IntervalTransform` into a no-op when the interval has zero length?

For at least the most fundamental case, the premise is that there's a uniform distribution with equal bounds, which doesn't sound particularly consistent in itself.  Perhaps something like the *limit* is well defined, but that's not what we're modeling here.

**Comment by ricardoV94** [comment]
> Does this only concern the case in which the upper and lower limits become -inf and inf, respectively. If so, isn't the result also no longer consistent—at least in the uniform case?

Yes this only concern that case, not the other limit where the edges are the same.

The uniform is no longer a proper distribution with such edges. But that's also the case for a uniform with -inf or +inf in only one of the edges, so I don't completely follow the argument.

What None, None represents is an interval transform from the real line back to the real line, which is a no-op, but so is a shift transform by zero or scale transform by one. I don't see how it creates any inconsistencies.

In any case, I don't have a strong opinion to keep or remove it. But if we remove it,  should we at least raise a ValueError when both edges are None?

**Comment by brandonwillard** [comment]
> What None, None represents is an interval transform from the real line back to the real line, which is a no-op, but so is a shift transform by zero or scale transform by one. I don't see how it creates any inconsistencies.

This is like arguing for the replacement `x -> x + 1 - 1` without any specific purpose.  In general, such "expansions" can be useful as intermediate steps in a larger system of rewrites (e.g. when they're needed to "reach" certain term graphs), but, without that context, they're simply deleterious.

Furthermore, such additions&mdash;when they do serve a project-relevant purpose&mdash;require the addition of canonicalization steps (e.g. `x + 1 - 1` to `x` in the example above to complete the `x == x + 1 - 1` relation being modeled).  In other words, the PR was incomplete without additional canonicalization steps.

> In any case, I don't have a strong opinion to keep or remove it. 

The important thing about this situation is that it doesn't appear to be a simple matter of opinion, but, instead, that **there are relevant objective reasons against having these changes** and&mdash;so far&mdash;none for keeping them.

Regarding interactions with other projects, as a rule of thumb no `aesara-devs` project should introduce changes for the purpose of other projects that do not also serve to further the `aesara-devs` project's domain objectives (in this case, the project's ability to represent/implement transforms) or its general quality.  This change appears to have served exclusively as a mild convenience for another project, and, without the negative effects described above, it would've been a neutral addition to the project at best.

We need to be clear on these principals so that we can avoid things like feature creep, incurring unnecessary ["technical debt"](https://en.wikipedia.org/wiki/Technical_debt), and the general build-up of design inconsistencies and byzantine work-arounds.

> But if we remove it, should we at least raise a ValueError when both edges are None?

Yes, definitely.

**Comment by brandonwillard** [comment]
> The uniform is no longer a proper distribution with such edges. But that's also the case for a uniform with -inf or +inf in only one of the edges, so I don't completely follow the argument.

The implication is that those changes allow one to specify inconsistent transforms.

**Comment by ricardoV94** [comment]
> This is like arguing for the replacement `x -> x + 1 - 1` without any specific purpose.  

Are we talking about the fact that the intermediate representation contains a `TransformedRV` instead of a `RandomVariable`? 

Because this doesn't change anything in the final logp graph. We are returning `value` in the forward and backward passes, which means the graph is the same as if we had use it directly without having a transform. The only change prior to aesara rewrites would be the `+0` term coming from the Jacobian. This is already optimized away by default, so in the end the graph is exactly the same as if we hadn't include the transform.


> The implication is that, when paired with certain distributions, the changes allow one to specify new types of inconsistent transforms; otherwise, no-ops.

This was already possible if you specified `IntervalTransform(lambda *inputs: inputs[-2], None )` for a Uniform distribution. We are not making any checks that the transforms you specify are "appropriate" for a given distribution (and I don't think it is our job, people might want to create non normalized distributions for some weird reason). Similarly, you can use a LogTransform to a Beta distribution if you wish to.
