### ISSUE TITLE
Numerical stability issues with the jacobian of transformed variables

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aeppl#86]
When dealing with transformed variables we first back-transform them so that they can be safely used as inputs to other downstream variables in here:

https://github.com/aesara-devs/aeppl/blob/18275e2bba83f21da5cde256bd67d86fa5b32451/aeppl/transforms.py#L145

However, we later have to forward-transform it again in order to compute the jacobian term:
https://github.com/aesara-devs/aeppl/blob/18275e2bba83f21da5cde256bd67d86fa5b32451/aeppl/transforms.py#L86-L87

This can lead to unnecessary numerical instability in models with complex transformations. The Interval transform is one such case and led to a PyMC performance regression documented in https://github.com/pymc-devs/pymc/issues/5088

```python
import aesara
import aesara.tensor as at
from aesara.compile.mode import Mode
from aeppl.transforms import IntervalTransform

a, b, x = at.scalars('a', 'b', 'x')
intvl = IntervalTransform(args_fn=lambda *args: (a, b))
graph = intvl.forward(intvl.backward(x))

graph_fn = aesara.function([a, b, x], graph, mode=Mode().excluding('fusion'))
aesara.dprint(graph_fn)
```

```
Elemwise{Sub}[(0, 0)] [id A] ''   9
 |Elemwise{Log}[(0, 0)] [id B] ''   7
 | |Elemwise{sub,no_inplace} [id C] ''   5
 |   |Elemwise{Add}[(0, 0)] [id D] ''   4
 |   | |Elemwise{mul,no_inplace} [id E] ''   1
 |   | | |Elemwise{sigmoid,no_inplace} [id F] ''   0
 |   | | | |x [id G]
 |   | | |b [id H]
 |   | |Elemwise{Mul}[(0, 0)] [id I] ''   3
 |   |   |Elemwise{Sub}[(0, 1)] [id J] ''   2
 |   |   | |TensorConstant{1.0} [id K]
 |   |   | |Elemwise{sigmoid,no_inplace} [id F] ''   0
 |   |   |a [id L]
 |   |a [id L]
 |Elemwise{Log}[(0, 0)] [id M] ''   8
   |Elemwise{Sub}[(0, 1)] [id N] ''   6
     |b [id H]
     |Elemwise{Add}[(0, 0)] [id D] ''   4
```

The graph is far from optimized and I don't see an elegant way how we could rewrite it away. This is probably true for the Simplex transform as well.

One alternative would be to make the original value variable an additional input of the TransformedRV, enabling us to use it directly when computing the jacobian term. This would also be future proof in that we don't need to add specialized rewrites for new transforms that may be added in aeppl or in PyMC

**Comment by brandonwillard** [comment]
If I understand this correctly, it sounds like an issue I had considered when first implementing these, and my plan was to eventually use `OpFromGraph` to represent the forward and backward transforms, then we could easily compute `f_inv(f(x)) -> x` exactly.  

In other words, we represent the transform operations explicitly in the graph so that they're easy to identify and "cancel".

**Comment by ricardoV94** [comment]
> If I understand this correctly, it sounds like an issue I had considered when first implementing these, and my plan was to eventually use `OpFromGraph` to represent the forward and backward transforms, then we could easily compute `f_inv(f(x)) -> x` exactly.
> 
> In other words, we represent the transform operations explicitly in the graph so that they're easy to identify and "cancel"—or simply extract original terms.

Yes that could be a nice solution as well.

**Comment by brandonwillard** [comment]
If we're only concerned with the Jacobian case, there are actually some much simpler things we could do.
