### ISSUE TITLE
Interference between new transforms and `tag.value_var`

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aeppl#92]
I didn't have time to figure out the source of the problem, but the test suite in PyMC started to fail multiple places with aeppl 0.0.16: 

https://github.com/pymc-devs/pymc/pull/5185/checks
https://github.com/pymc-devs/pymc/pull/5159/checks

**Comment by ricardoV94** [comment]
Here is a PyMC snippet that behaves differently between aeppl `0.0.16` and `0.0.15`

```python
import pymc as pm
import numpy as np
data = pm.floatX(np.zeros(10))
with pm.Model() as m:
    p = pm.Beta("p", 1, 1)
    obs = pm.Bernoulli("obs", p=p, observed=data)
print(pm.logpt(obs).eval({p.tag.value_var: pm.floatX(np.array(0.0))}))
```

I couldn't get a MWE using aeppl directly yet.

**Comment by brandonwillard** [comment]
Please, do **not** create generic PyMC issues in this repository.  Create an issue in PyMC and work out the AePPL-specific problem/question(s) _then_ create an issue in this repository for those.

**Comment by ricardoV94** [comment]
Here is the problem. Aeppl's `rvs_to_values` is still checking for `value_var` in tag and this screws up the replacements with the new transforms.

```python
import aesara.tensor as at
import aeppl
import aeppl.transforms

p = at.random.beta(1, 1)
obs = at.random.bernoulli(p)

p_val = p.type()
obs_val = obs.type()

tr = aeppl.transforms.TransformValuesOpt({p_val: aeppl.transforms.LogOddsTransform()})

p.tag.value_var = p_val
logp = aeppl.factorized_joint_logprob({obs: obs_val, p: p_val}, extra_rewrites=tr)

logp[obs_val].eval({p_val: 0, obs_val: 0})
```
You can the right result if `p.tag.value_var = p_val` is ommited

**Comment by ricardoV94** [comment]
Do we still (or ever needed) to work with the `.tag` attributes in `aeppl`?

**Comment by brandonwillard** [comment]
> Do we still (or ever needed) to work with the `.tag` attributes in `aeppl`?

No, not here at least.
